examples/dev-quick-test/ex-000.js, plugins/annotations.js
https://github.com/TargetProcess/tauCharts/issues/99
=> Fix annotation text position (#99)

plugins/annotations.js, src/elements/decorators/layer-labels.js, src/elements/element.line.js
Fixed empty path length calls, sort handler, missing Array.prototype.find.
=> Linechart IE11 bugs

Gruntfile.js, examples/dev-quick-test/ex-055.js, examples/dev.js, examples/index.html
Removed ES6 features. Use script counter for IE. Fixed `export` plugin reference.
=> Fixed errors seen in IE11

src/elements/coords.cartesian.js, src/utils/d3-decorators.js, test/utils.test.js
Run collision detection immediately. Filter active (not removed) ticks.
=> Axes labels collision blink

src/utils/d3-decorators.js, test/utils.test.js
Use `transform` attribute to move overlapping labels.
=> Unstable axes labels collision detection

less/layout.less, src/utils/utils-dom.js
Manually toggle overflow scroll/hidden.
=> Chrome overflow auto crash

Gruntfile.js, README.md, examples/dev-quick-test/ex-000.js, examples/dev-quick-test/ex-011.js, examples/dev-quick-test/ex-017.js, examples/dev-quick-test/ex-040.js, examples/dev-quick-test/ex-050.js, examples/dev-quick-test/ex-055.js, examples/dev-temp-gpl-test.html, examples/dev.js, examples/index.html, examples/specs/ex-002.js, examples/specs/ex-003.js, examples/specs/ex-005.js, examples/specs/ex-009.js, examples/specs/ex-010.js, examples/specs/ex-012.js, examples/specs/ex-013.js, examples/specs/ex-014.js, examples/specs/ex-015.js, examples/specs/whiskers.js
Remove underscore from readme, example, etc.
=> Remove underscore 3

src/elements/decorators/layer-labels-annealing-simulator.js, src/elements/decorators/layer-labels-penalties.js, src/elements/decorators/layer-labels.js, src/elements/element.point.js, src/utils/utils-dom.js
Add rule to hide label if it intersects with points
=> Fix annealing simulator algorithm

src/utils/path/interpolators/path-points.js, src/utils/path/svg/brush-line.js, src/utils/utils.js
Use fast unique implementation O(n)
=> Fix https://github.com/TargetProcess/tauCharts/issues/283

plugins/tooltip.js
* Fixed Tooltip API compatibility.
* Don't hide sticked tooltip on mouse leave.
* Hide tooltip on resize.
=> Fixed Tooltip API compatibility and minor bugs

less/plugins/tooltip.less, less/tauCharts.less, plugins/tooltip.js, src/elements/element.interval.js, src/elements/element.js, src/elements/element.path.base.js, src/elements/element.point.js, src/utils/utils.js, test/element-area.test.js, test/element-path.test.js, test/tooltip-plugin.test.js
- Show pointer cursor for clickable elements.
- Show tooltip near cursor.
- Smoothly update tooltip position.
- Prevent highlighting other elements after click.
- Show highlighted element over others.
=> Improved Tooltip cursor

less/plugins/tooltip.less, less/tauCharts.less, plugins/tooltip.js, src/charts/tau.plot.js, src/elements/element.area.js, src/elements/element.interval.js, src/elements/element.js, src/elements/element.line.js, src/elements/element.path.base.js, src/elements/element.path.js, src/elements/element.point.js, src/tau.charts.js, src/utils/utils-draw.js, test/api-chart.test.js, test/element-area.test.js, test/element-interval.test.js, test/element-line.test.js, test/element-path.test.js, test/element-point.test.js, test/tests-main.js, test/tooltip-plugin.test.js, test/utils/utils.js
- Highlight element when cursor is close to it.
- Highlight line point or bar when cursor is close to value.
- Highlight overlapped points, line points.
- Raise highlighted lines, bar and point groups.
- When element is clicked, dim other elements.
- Minor improvements.
=> Improved highlight and tooltip behavior

less/plugins/legend.less, plugins/legend.js, test/legend-plugin.test.js
- Focus on single color on click.
- Toggle color on item click.
- Reset button.
=> Improve color legend behavior

plugins/legend.js, plugins/tooltip.js, src/elements/element.point.js
- Prevent legend from highlighting clicked element.
- Fixed highlighting filtered points.
- Fixed predefined disabled legend items icon.
=> Fixed tooltip and legend highlight conflict

less/plugins/tooltip.less, less/tauCharts.less, src/elements/element.path.base.js
- Show X-cursor line for highlighted line point.
- Fixed tooltip padding around cursor.
=> Show X-cursor line for highlighted line point

less/plugins/crosshair.less, plugins/crosshair.js, src/plugins-sdk.js, src/tau.charts.js
- Colorful label boxes.
- Display labels over axis ticks.
- Fixed labels overflow.
- Fixed displaying labels over floating axes.
=> Crosshair style improvements

plugins/crosshair.js
Exclude zero values from Crosshair total calculation.
=> Fixed wrong Crosshair position for Stacked Bar

less/plugins/quick-filter.less, less/tauCharts.less, plugins/quick-filter.js, src/elements/coords.parallel.js, src/elements/element.parallel.line.js
- Fixed Quick Filter brush.
- Fixed Parallel Coords brush.
=> Use D3 v4 brush

src/definitions.d.ts, src/elements/element.area.ts, src/elements/element.path.base.js, src/utils/utils-position.ts
- Highlight proper area under cursor.
=> Area closest element search

examples/dev-quick-test/ex-055.js, plugins/floating-axes.js, plugins/quick-filter.js, src/charts/tau.plot.ts, src/elements/coords.geomap.js, src/elements/coords.parallel.js, src/elements/element.ts
- d3.event can be accessed using `import * as d3_selection from 'd3-selection'; d3_selection.event;`
=> d3.event get lost

examples/specs/time-interval.js, plugins/annotations.js
- Fixed passing uppercase colors into a brewer.
=> Fixed missing Annotation line

examples/specs/time-interval.js, src/grammar-registry.ts, src/scales/time.ts, src/spec-converter.ts, test/scales-factory.test.js
- Adjust min and max of time scale with intervals.
- Fixed extending scale with same domain start and end.
=> Adjust limits of time scale with intervals.

bower.json, karma.conf.js, plugins/export-to.js, tasks/gulp-js.js
- Updated rgb-color dependency.
- Log Export error messages.
=> Fix export to PNG

less/plugins/diff-tooltip.less, plugins/diff-tooltip.ts, plugins/diff-tooltip/diff-template.ts, plugins/diff-tooltip/interval-highlight.ts, plugins/tooltip/fields-template.ts, src/utils/polyfills.js
- Show diff for field when no color encoding.
- Fixed IE11 compatibility.
=> Diff Tooltip improvements

less/plugins/diff-tooltip.less, less/plugins/tooltip.less, less/themes/dark/theme.less, less/themes/default/theme.less, plugins/diff-tooltip/diff-template.ts, plugins/geomap-tooltip.js, plugins/parallel-tooltip.js, plugins/tooltip/fields-template.ts, plugins/tooltip/tooltip.ts
- Place Tooltip buttons horizontally.
- Slide from top or bottom (closer to cursor).
- Show color diff when more than 1 item.
=> Horizontal Tooltip buttons.

examples/index.js, examples/specs/time-interval-missing-data.js, plugins/diff-tooltip.ts, plugins/diff-tooltip/diff-template.ts, src/elements/decorators/anchors.ts, src/elements/element.area.ts, src/elements/element.line.js, src/elements/element.path.base.js, src/grammar-registry.ts, src/utils/utils-grammar.ts, test/chart-line.test.js
- Generate data for missing periods (line and area charts).
- Properly highlight missing time intervals.
- Show diff for missing but previously available group.
=> Draw lines at zero and show diff for missing time intervals

examples/index.js, plugins/diff-tooltip.ts, plugins/diff-tooltip/diff-template.ts, src/elements/decorators/anchors.ts, src/elements/element.path.base.js, src/grammar-registry.ts
- Fixed removing line anchors after exclude.
- Fixed single field diff when previous value missing.
- Fixed sorting examples within one file.
=> Fixed removing line anchors after exclude

gulpfile.js, package.json, tasks/gulp-watch.js
=> Ability to set dev port from CLI

plugins/export-to.js, src/charts/tau.plot.ts
- Fixed unsubscribing Export event.
- Clear filters on update.
=> Fixed exporting multiple files after update

bower.json, examples/index.js, examples/specs/update-config.js, karma.conf.js, plugins/export-to.js, tasks/gulp-js.js
- Replaced fetch with XMLHttpRequest.
- Fixed dev page errors in IE.
=> Untied Export from Promise and fetch polyfills

examples/specs/annotation-types.js, plugins/annotations.ts, src/charts/tau.plot.ts, src/definitions.d.ts, src/scales-registry.ts
- Add annotation values into scale series config.
- Animate annotations during filtering.
=> Allow annotation to change the scale

plugins/annotations.ts
=> Display annotation value

.travis.yml, package.json, tasks/gulp-js.js, tasks/rollup-plugin-replace-bundle.js
- Modify `canvg` bundle for use with `use strict`.
=> Fixed export to PNG with smooth interpolation

package.json, plugins/annotations.ts, plugins/export-to.js, plugins/floating-axes.js, plugins/geomap-legend.js, plugins/layers.js, plugins/legend.js, plugins/quick-filter.js, plugins/settings.js, plugins/trendline.js
- Run TSLint before build.
- Run TSLint before tests.
- Enabled TSLint for JS plugins, fixed warnings.
=> Run TSLint before build and tests

plugins/diff-tooltip/interval-highlight.ts, src/elements/coords.cartesian.axis.ts, src/utils/utils.ts
- Hide axis domain line when necessary
- Refactored pipeline utility
=>  Hide axis domain line when necessary

plugins/annotations.ts, plugins/trendline.js, test/trendline-plugin.test.js
- apply trendline plugins only for chart element
- fix generating data refs for trendline plugins
=> #511 fix trendline and annotations plugins

examples/index.js, examples/specs/multiline-label.js, src/definitions.d.ts, src/elements/decorators/layer-labels-model.ts, src/elements/decorators/layer-labels-rules.ts, src/elements/decorators/layer-labels.ts, src/utils/utils-dom.ts, test/chart-bar.test.js, test/layer-titles-rules.test.js, test/utils.test.js
- Multiline labels support (using lineBreak and lineBreakSeparator flags for label guide)
=> Multiline labels

src/elements/decorators/layer-labels-model.ts, src/elements/decorators/layer-labels-rules.ts, src/elements/decorators/layer-labels.ts, src/utils/utils.ts, test/chart-bar.test.js, test/layer-titles-rules.test.js, test/utils.test.js
- Center multiline labels if label angle = 0
- Left align multiline labels if angle not 0
- Cut each of label lines correctly in case if overflow
=> multiline label improvements.

plugins/legend.js, src/elements/coords.cartesian.axis.ts, src/utils/utils-draw.ts, test/legend-plugin.test.js, test/utils.test.js
- Fix order for dates in Color legend when scale is periodic
- Improve cutting facet label logic
=> Facet and legend improvements

plugins/annotations.ts, src/formatter-registry.ts
- fix ticks positioning in case annotation adds new ticks
- apply null tick formatting for empty string tick
=> annotation and empty string ticks

plugins/legend.js
Now we can add handler on color select and set initial selected categories.
```js
legend({
selectedCategories: [`test`],
onSelect({selectedCategories}) {
// will be triggered when user click on some color in legend
}
})
```
=> Add onSelect settings and initial selected categories for legend plugin

plugins/legend.js, src/spec-transform-auto-layout.ts, test/spec-transform-auto-layout.test.js
- now user can set rotate guide params for x dimensions both with auto layout spec 
- add type event for onSelect legend plugin method
=> Apply user defined guide for auto layout
